export enum ApplicationError {
  ADD_BOOK = "No se ha podido añadir el libro",
  ADD_LOAN = "Error al añadir el préstamo",
  ALREADY_RETURNED = "El libro ya ha sido retornado",
  CREATE_USER = "Se ha producido un error al crear el usuario",
  DELETE_BOOK = "Error al eliminar el libro",
  DELETE_LOAN = "Error en la eliminación del préstamo",
  GET_ACTIVE_LOANS = "Error al buscar préstamos activos",
  GET_BOOK = "No ha podido obtenerse el libro",
  GET_BOOKS = "Ha habido un problema en la obtención del catálogo de libros",
  GET_USER_BY_EMAIL = "Se ha producido un error al buscar el usuario por email",
  GET_USER_BY_ID = "Error al buscar la id de usuario",
  LOAD_CATALOG = "Error al recuperar el diálogo",
  LOGIN = "Error en el login",
  MINIMUM_COPY = "Para registrar un nuevo libro es necesario disponer de una copia como mínimo",
  NEW_LOAN = "No ha podido realizarse el préstamo. Disculpe las molestias",
  NOT_FOUND = "No encontrado",
  NOT_FOUND_BOOK = "Libro no encontrado",
  NO_COPIES_AVAILABLE = "No hay copias disponibles",
  RETURN_BOOK = "Error al devolver el libro",
  RETURN_BOOK_TRY_AGAIN = "Hubo un error al devolver el libro, por favor intente nuevamente",
  SAVE_BOOK = "Se ha producido un error al guardar el libro",
  SAVE_COPIES = "Error al actualizar las copias disponibles",
  SAVE_LOAN = "Error al añadir un nuevo préstamo",
  SAVE_USER = "No hemos podido guardar el usuario",
  UPDATE_BOOK = "Ha habido un error al actualizar el libro",
  WRONG_CREDENTIALS = "Credenciales incorrectas",
}
